set_property SRC_FILE_INFO {cfile:C:/Users/4trav/Desktop/ECE_Labs/ECE_316_Labs/lab2/lab2_AND_Gate/lab2_AND_Gate.srcs/constrs_1/new/Basys3_myAND.xdc rfile:../../../lab2_AND_Gate.srcs/constrs_1/new/Basys3_myAND.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {b}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {a}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {out}]
