set_property SRC_FILE_INFO {cfile:C:/Users/4trav/Desktop/ECE_Labs/ECE_316_Labs/lab3/rising_edge_detector/rising_edge_detector.srcs/constrs_1/new/Basys3_rising_edge_detector.xdc rfile:../../../rising_edge_detector.srcs/constrs_1/new/Basys3_rising_edge_detector.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {signal}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {outedge}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports {reset}]
