set_property SRC_FILE_INFO {cfile:C:/Users/4trav/Desktop/ECE_Labs/ECE_316_Labs/lab3/flight_attendant/flight_attendant.srcs/constrs_1/new/Basys3_flight_attendant.xdc rfile:../../../flight_attendant.srcs/constrs_1/new/Basys3_flight_attendant.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports {call_button}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {cancel_button}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {light_state}]
